name: wasm ci

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - "develop"
      - "master"
      - "pkg/*"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build-test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        rustup target add wasm32-unknown-unknown
    - name: Build
      run: |
        cargo build --target wasm32-unknown-unknown --no-default-features
